version: '3'
services:
  dev:
    image: keboolabot/keboola-processor-split-dev
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - ./:/code:z
      - ./data:/data:z
      - cache:/tmp/cache

volumes:
  cache:
